spring.application.name=enotes-api


server.port=8085
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/enotes_dev
spring.datasource.username=root
spring.datasource.password=Vinod@6891

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload.path = notes/
spring.servlet.multipart.max-file-size= 100MB
spring.servlet.multipart.max-request-size=100MB

# Email Send configuration

spring.mail.host=smtp.gmail.com
spring.mail.username=vin.sajgure@gmail.com
spring.mail.password=txgfvwdhhpgktdnp
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
