spring:
  application:
    name: enotes-api
  profiles:
      active: dev

---
# Dev profile configuration   
spring:
  config:
      activate: 
        on-profile: dev
  datasource:
    username: root
    password: Vinod@6891
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enotes_dev      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: 'true' 
        format_sql: 'true'
        
    hibernate:
      ddl-auto: none
            
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  
  mail:
    host: smtp.gmail.com
    username: vin.sajgure@gmail.com
    password: txgfvwdhhpgktdnp
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
server:
  port: '8080'  
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /enotes-docs          
  api-docs:
    path: /enotes-api-docs
file:
  upload:
    path: notes/

  
---  
# Test profile configuration   
spring:
  config:
      activate: 
        on-profile: test
  datasource:
    username: root
    password: Vinod@6891
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enotes_dev      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
    hibernate:
      ddl-auto: none
    
    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  
  mail:
    host: smtp.gmail.com
    username: vin.sajgure@gmail.com
    password: txgfvwdhhpgktdnp
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
server:
  port: '8081'  
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /enotes-docs          
  api-docs:
    path: /enotes-api-docs
file:
  upload:
    path: notes/
--- 

# UAT profile configuration   
spring:
  config:
      activate: 
        on-profile: uat
  datasource:
    username: root
    password: Vinod@6891
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enotes_dev      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
    hibernate:
      ddl-auto: none
   
    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  
  mail:
    host: smtp.gmail.com
    username: vin.sajgure@gmail.com
    password: txgfvwdhhpgktdnp
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
server:
  port: '8082'            
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /enotes-docs          
  api-docs:
    path: /enotes-api-docs          
          
file:
  upload:
    path: notes/
---  
# PROD profile configuration   
spring:
  config:
      activate: 
        on-profile: prod
  datasource:
    username: root
    password: Vinod@6891
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enotes_dev      
  jpa:
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
    hibernate:
      ddl-auto: none
    
    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  
  mail:
    host: smtp.gmail.com
    username: vin.sajgure@gmail.com
    password: txgfvwdhhpgktdnp
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
server:
  port: '8080'            
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /enotes-docs          
  api-docs:
    path: /enotes-api-docs          
file:
  upload:
    path: notes/

    
    